// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectLocale = `-- name: AddProjectLocale :exec
INSERT INTO project_locales (project_id,locale) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type AddProjectLocaleParams struct {
	ProjectID int64  `json:"project_id"`
	Locale    string `json:"locale"`
}

func (q *Queries) AddProjectLocale(ctx context.Context, arg AddProjectLocaleParams) error {
	_, err := q.db.Exec(ctx, addProjectLocale, arg.ProjectID, arg.Locale)
	return err
}

const claimDelivery = `-- name: ClaimDelivery :one
SELECT delivery_id, received_at, repository_url, ref, status, error FROM webhook_deliveries WHERE status='pending' ORDER BY received_at FOR UPDATE SKIP LOCKED LIMIT 1
`

func (q *Queries) ClaimDelivery(ctx context.Context) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, claimDelivery)
	var i WebhookDelivery
	err := row.Scan(
		&i.DeliveryID,
		&i.ReceivedAt,
		&i.RepositoryUrl,
		&i.Ref,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const componentHistory = `-- name: ComponentHistory :many
SELECT h.id,h.unit_id,un.key,h.locale,h.value,h.status,h.version,h.changed_at,h.changed_by,coalesce(u.name,'')::text AS changed_by_name
FROM translation_history h JOIN units un ON un.id=h.unit_id LEFT JOIN users u ON u.id=h.changed_by
WHERE un.component_id=$1 AND ($2::text = '' OR h.locale=$2) ORDER BY h.id DESC LIMIT 100
`

type ComponentHistoryParams struct {
	ComponentID int64  `json:"component_id"`
	Locale      string `json:"locale"`
}

type ComponentHistoryRow struct {
	ID            int64              `json:"id"`
	UnitID        int64              `json:"unit_id"`
	Key           string             `json:"key"`
	Locale        string             `json:"locale"`
	Value         string             `json:"value"`
	Status        string             `json:"status"`
	Version       int64              `json:"version"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
	ChangedBy     pgtype.Int8        `json:"changed_by"`
	ChangedByName string             `json:"changed_by_name"`
}

func (q *Queries) ComponentHistory(ctx context.Context, arg ComponentHistoryParams) ([]ComponentHistoryRow, error) {
	rows, err := q.db.Query(ctx, componentHistory, arg.ComponentID, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentHistoryRow{}
	for rows.Next() {
		var i ComponentHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Key,
			&i.Locale,
			&i.Value,
			&i.Status,
			&i.Version,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const componentStats = `-- name: ComponentStats :many
SELECT pl.locale,
 count(u.id)::bigint AS total,
 count(t.unit_id) FILTER (WHERE t.status IN ('translated','reviewed'))::bigint AS translated,
 count(t.unit_id) FILTER (WHERE t.status = 'reviewed')::bigint AS reviewed,
 count(t.unit_id) FILTER (WHERE t.status = 'needs_review')::bigint AS needs_review
FROM components c JOIN project_locales pl ON pl.project_id=c.project_id
LEFT JOIN units u ON u.component_id=c.id
LEFT JOIN translations t ON t.unit_id=u.id AND t.locale=pl.locale
WHERE c.id=$1 GROUP BY pl.locale ORDER BY pl.locale
`

type ComponentStatsRow struct {
	Locale      string `json:"locale"`
	Total       int64  `json:"total"`
	Translated  int64  `json:"translated"`
	Reviewed    int64  `json:"reviewed"`
	NeedsReview int64  `json:"needs_review"`
}

func (q *Queries) ComponentStats(ctx context.Context, id int64) ([]ComponentStatsRow, error) {
	rows, err := q.db.Query(ctx, componentStats, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentStatsRow{}
	for rows.Next() {
		var i ComponentStatsRow
		if err := rows.Scan(
			&i.Locale,
			&i.Total,
			&i.Translated,
			&i.Reviewed,
			&i.NeedsReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnits = `-- name: CountUnits :one
SELECT count(*)::bigint FROM units u LEFT JOIN translations t ON t.unit_id=u.id AND t.locale=$1
WHERE u.component_id=$2
 AND ($3::text = '' OR u.key ILIKE $3 OR u.source ILIKE $3 OR t.value ILIKE $3)
 AND ($4::text = '' OR coalesce(t.status,'untranslated') = $4)
`

type CountUnitsParams struct {
	Locale      string `json:"locale"`
	ComponentID int64  `json:"component_id"`
	Query       string `json:"query"`
	Status      string `json:"status"`
}

func (q *Queries) CountUnits(ctx context.Context, arg CountUnitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnits,
		arg.Locale,
		arg.ComponentID,
		arg.Query,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (project_id,slug,name,format,repository_id,file_pattern) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, project_id, slug, name, format, file_pattern, repository_id
`

type CreateComponentParams struct {
	ProjectID    int64       `json:"project_id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	Format       string      `json:"format"`
	RepositoryID pgtype.Int8 `json:"repository_id"`
	FilePattern  string      `json:"file_pattern"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.Format,
		arg.RepositoryID,
		arg.FilePattern,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Format,
		&i.FilePattern,
		&i.RepositoryID,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug,name,source_locale) VALUES ($1,$2,$3) RETURNING id, slug, name, source_locale, created_at
`

type CreateProjectParams struct {
	Slug         string `json:"slug"`
	Name         string `json:"name"`
	SourceLocale string `json:"source_locale"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Slug, arg.Name, arg.SourceLocale)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceLocale,
		&i.CreatedAt,
	)
	return i, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (project_id,name,url,branch) VALUES ($1,$2,$3,$4) RETURNING id, project_id, name, url, branch, created_at
`

type CreateRepositoryParams struct {
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
	Url       string `json:"url"`
	Branch    string `json:"branch"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.ProjectID,
		arg.Name,
		arg.Url,
		arg.Branch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.Branch,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash,user_id,expires_at) VALUES ($1,$2,$3)
`

type CreateSessionParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email,password_hash,name,admin) VALUES ($1,$2,$3,$4) RETURNING id, email, password_hash, name, admin, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
	Admin        bool   `json:"admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Admin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :execrows
DELETE FROM components WHERE id=$1
`

func (q *Queries) DeleteComponent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComponent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteGlossaryTerm = `-- name: DeleteGlossaryTerm :execrows
DELETE FROM glossary_terms WHERE id=$1 AND project_id=$2
`

type DeleteGlossaryTermParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) DeleteGlossaryTerm(ctx context.Context, arg DeleteGlossaryTermParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGlossaryTerm, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLocale = `-- name: DeleteLocale :execrows
DELETE FROM locales WHERE code=$1
`

func (q *Queries) DeleteLocale(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocale, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM memberships WHERE project_id=$1 AND user_id=$2
`

type DeleteMemberParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.ProjectID, arg.UserID)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id=$1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRepository = `-- name: DeleteRepository :execrows
DELETE FROM repositories WHERE id=$1
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRepository, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash=$1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const enqueueDelivery = `-- name: EnqueueDelivery :execrows
INSERT INTO webhook_deliveries (delivery_id,repository_url,ref) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type EnqueueDeliveryParams struct {
	DeliveryID    string `json:"delivery_id"`
	RepositoryUrl string `json:"repository_url"`
	Ref           string `json:"ref"`
}

func (q *Queries) EnqueueDelivery(ctx context.Context, arg EnqueueDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueDelivery, arg.DeliveryID, arg.RepositoryUrl, arg.Ref)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureLocale = `-- name: EnsureLocale :exec
INSERT INTO locales (code,name) VALUES ($1,$2) ON CONFLICT (code) DO NOTHING
`

type EnsureLocaleParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) EnsureLocale(ctx context.Context, arg EnsureLocaleParams) error {
	_, err := q.db.Exec(ctx, ensureLocale, arg.Code, arg.Name)
	return err
}

const exactMemoryMatches = `-- name: ExactMemoryMatches :many
SELECT u.id AS unit_id, u.key, coalesce((
 SELECT t.value FROM units u2 JOIN translations t ON t.unit_id=u2.id AND t.locale=$1
 JOIN components c2 ON c2.id=u2.component_id
 WHERE u2.source=u.source AND u2.id<>u.id AND t.value<>''
  AND ($2::boolean OR EXISTS (SELECT 1 FROM memberships m WHERE m.project_id=c2.project_id AND m.user_id=$3))
 ORDER BY (t.status='reviewed') DESC, t.updated_at DESC LIMIT 1), '')::text AS value
FROM units u LEFT JOIN translations t0 ON t0.unit_id=u.id AND t0.locale=$1
WHERE u.component_id=$4 AND t0.unit_id IS NULL AND u.source <> ''
ORDER BY u.key
`

type ExactMemoryMatchesParams struct {
	Locale      string `json:"locale"`
	IsAdmin     bool   `json:"is_admin"`
	UserID      int64  `json:"user_id"`
	ComponentID int64  `json:"component_id"`
}

type ExactMemoryMatchesRow struct {
	UnitID int64  `json:"unit_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

func (q *Queries) ExactMemoryMatches(ctx context.Context, arg ExactMemoryMatchesParams) ([]ExactMemoryMatchesRow, error) {
	rows, err := q.db.Query(ctx, exactMemoryMatches,
		arg.Locale,
		arg.IsAdmin,
		arg.UserID,
		arg.ComponentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExactMemoryMatchesRow{}
	for rows.Next() {
		var i ExactMemoryMatchesRow
		if err := rows.Scan(&i.UnitID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUnit = `-- name: FindUnit :one
SELECT id, component_id, key, source FROM units WHERE component_id=$1 AND key=$2
`

type FindUnitParams struct {
	ComponentID int64  `json:"component_id"`
	Key         string `json:"key"`
}

func (q *Queries) FindUnit(ctx context.Context, arg FindUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, findUnit, arg.ComponentID, arg.Key)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Key,
		&i.Source,
	)
	return i, err
}

const finishDelivery = `-- name: FinishDelivery :exec
UPDATE webhook_deliveries SET status=$2,error=$3 WHERE delivery_id=$1
`

type FinishDeliveryParams struct {
	DeliveryID string `json:"delivery_id"`
	Status     string `json:"status"`
	Error      string `json:"error"`
}

func (q *Queries) FinishDelivery(ctx context.Context, arg FinishDeliveryParams) error {
	_, err := q.db.Exec(ctx, finishDelivery, arg.DeliveryID, arg.Status, arg.Error)
	return err
}

const getComponent = `-- name: GetComponent :one
SELECT id, project_id, slug, name, format, file_pattern, repository_id FROM components WHERE id=$1
`

func (q *Queries) GetComponent(ctx context.Context, id int64) (Component, error) {
	row := q.db.QueryRow(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Format,
		&i.FilePattern,
		&i.RepositoryID,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT component_id, locale, content FROM documents WHERE component_id=$1 AND locale=$2
`

type GetDocumentParams struct {
	ComponentID int64  `json:"component_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ComponentID, arg.Locale)
	var i Document
	err := row.Scan(&i.ComponentID, &i.Locale, &i.Content)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, slug, name, source_locale, created_at FROM projects WHERE id=$1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceLocale,
		&i.CreatedAt,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, project_id, name, url, branch, created_at FROM repositories WHERE id=$1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.Branch,
		&i.CreatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT role FROM memberships WHERE project_id=$1 AND user_id=$2
`

type GetRoleParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, component_id, key, source FROM units WHERE id=$1
`

func (q *Queries) GetUnit(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Key,
		&i.Source,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, admin, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Admin,
		&i.CreatedAt,
	)
	return i, err
}

const glossaryMatches = `-- name: GlossaryMatches :many
SELECT id, project_id, locale, term, translation, note, updated_by, updated_at FROM glossary_terms WHERE project_id=$1 AND locale=$2 AND position(lower(term) IN lower($3)) > 0 ORDER BY length(term) DESC, term
`

type GlossaryMatchesParams struct {
	ProjectID int64  `json:"project_id"`
	Locale    string `json:"locale"`
	Source    string `json:"source"`
}

func (q *Queries) GlossaryMatches(ctx context.Context, arg GlossaryMatchesParams) ([]GlossaryTerm, error) {
	rows, err := q.db.Query(ctx, glossaryMatches, arg.ProjectID, arg.Locale, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlossaryTerm{}
	for rows.Next() {
		var i GlossaryTerm
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Locale,
			&i.Term,
			&i.Translation,
			&i.Note,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importTranslation = `-- name: ImportTranslation :exec
INSERT INTO translations (unit_id,locale,value,updated_by) VALUES ($1,$2,$3,$4)
ON CONFLICT (unit_id,locale) DO UPDATE SET value=excluded.value,status='translated',version=translations.version+1,updated_by=excluded.updated_by,updated_at=now()
WHERE translations.value IS DISTINCT FROM excluded.value
`

type ImportTranslationParams struct {
	UnitID    int64       `json:"unit_id"`
	Locale    string      `json:"locale"`
	Value     string      `json:"value"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) ImportTranslation(ctx context.Context, arg ImportTranslationParams) error {
	_, err := q.db.Exec(ctx, importTranslation,
		arg.UnitID,
		arg.Locale,
		arg.Value,
		arg.UpdatedBy,
	)
	return err
}

const listComponents = `-- name: ListComponents :many
SELECT id, project_id, slug, name, format, file_pattern, repository_id FROM components WHERE project_id=$1 ORDER BY name
`

func (q *Queries) ListComponents(ctx context.Context, projectID int64) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponents, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.Format,
			&i.FilePattern,
			&i.RepositoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT delivery_id, received_at, repository_url, ref, status, error FROM webhook_deliveries ORDER BY received_at DESC LIMIT 100
`

func (q *Queries) ListDeliveries(ctx context.Context) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.DeliveryID,
			&i.ReceivedAt,
			&i.RepositoryUrl,
			&i.Ref,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlossary = `-- name: ListGlossary :many
SELECT g.id, g.project_id, g.locale, g.term, g.translation, g.note, g.updated_by, g.updated_at, coalesce(u.name,'')::text AS updated_by_name FROM glossary_terms g LEFT JOIN users u ON u.id=g.updated_by
WHERE g.project_id=$1 AND ($2::text = '' OR g.locale=$2) ORDER BY lower(g.term), g.locale
`

type ListGlossaryParams struct {
	ProjectID int64  `json:"project_id"`
	Locale    string `json:"locale"`
}

type ListGlossaryRow struct {
	ID            int64              `json:"id"`
	ProjectID     int64              `json:"project_id"`
	Locale        string             `json:"locale"`
	Term          string             `json:"term"`
	Translation   string             `json:"translation"`
	Note          string             `json:"note"`
	UpdatedBy     pgtype.Int8        `json:"updated_by"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UpdatedByName string             `json:"updated_by_name"`
}

func (q *Queries) ListGlossary(ctx context.Context, arg ListGlossaryParams) ([]ListGlossaryRow, error) {
	rows, err := q.db.Query(ctx, listGlossary, arg.ProjectID, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlossaryRow{}
	for rows.Next() {
		var i ListGlossaryRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Locale,
			&i.Term,
			&i.Translation,
			&i.Note,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.UpdatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocales = `-- name: ListLocales :many
SELECT code, name FROM locales ORDER BY code
`

func (q *Queries) ListLocales(ctx context.Context) ([]Locale, error) {
	rows, err := q.db.Query(ctx, listLocales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Locale{}
	for rows.Next() {
		var i Locale
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id,u.email,u.name,m.role FROM memberships m JOIN users u ON u.id=m.user_id WHERE project_id=$1 ORDER BY u.email
`

type ListMembersRow struct {
	UserID int64  `json:"user_id"`
	Email  string `json:"email"`
	Name   string `json:"name"`
	Role   string `json:"role"`
}

func (q *Queries) ListMembers(ctx context.Context, projectID int64) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.slug, p.name, p.source_locale, p.created_at FROM projects p WHERE $1::boolean OR EXISTS (SELECT 1 FROM memberships m WHERE m.project_id=p.id AND m.user_id=$2) ORDER BY p.name
`

type ListProjectsParams struct {
	IsAdmin bool  `json:"is_admin"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SourceLocale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, project_id, name, url, branch, created_at FROM repositories WHERE project_id=$1 ORDER BY name
`

func (q *Queries) ListRepositories(ctx context.Context, projectID int64) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Url,
			&i.Branch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT u.id,u.key,u.source,coalesce(t.value,'')::text AS value,coalesce(t.status,'untranslated')::text AS status,coalesce(t.version,0)::bigint AS version,t.updated_at
FROM units u LEFT JOIN translations t ON t.unit_id=u.id AND t.locale=$1
WHERE u.component_id=$2
 AND ($3::text = '' OR u.key ILIKE $3 OR u.source ILIKE $3 OR t.value ILIKE $3)
 AND ($4::text = '' OR coalesce(t.status,'untranslated') = $4)
ORDER BY u.key LIMIT $6 OFFSET $5
`

type ListUnitsParams struct {
	Locale      string `json:"locale"`
	ComponentID int64  `json:"component_id"`
	Query       string `json:"query"`
	Status      string `json:"status"`
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
}

type ListUnitsRow struct {
	ID        int64              `json:"id"`
	Key       string             `json:"key"`
	Source    string             `json:"source"`
	Value     string             `json:"value"`
	Status    string             `json:"status"`
	Version   int64              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits,
		arg.Locale,
		arg.ComponentID,
		arg.Query,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitsRow{}
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Source,
			&i.Value,
			&i.Status,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id,email,name,admin,created_at FROM users ORDER BY id
`

type ListUsersRow struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Admin     bool               `json:"admin"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Admin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNeedsReview = `-- name: MarkNeedsReview :exec
UPDATE translations SET status='needs_review',version=version+1,updated_by=NULL,updated_at=now() WHERE unit_id=$1 AND status <> 'needs_review'
`

func (q *Queries) MarkNeedsReview(ctx context.Context, unitID int64) error {
	_, err := q.db.Exec(ctx, markNeedsReview, unitID)
	return err
}

const projectHistory = `-- name: ProjectHistory :many
SELECT h.id,h.unit_id,un.key,un.component_id,c.name AS component_name,h.locale,h.value,h.status,h.version,h.changed_at,h.changed_by,coalesce(u.name,'')::text AS changed_by_name
FROM translation_history h JOIN units un ON un.id=h.unit_id JOIN components c ON c.id=un.component_id LEFT JOIN users u ON u.id=h.changed_by
WHERE c.project_id=$1 ORDER BY h.id DESC LIMIT 100
`

type ProjectHistoryRow struct {
	ID            int64              `json:"id"`
	UnitID        int64              `json:"unit_id"`
	Key           string             `json:"key"`
	ComponentID   int64              `json:"component_id"`
	ComponentName string             `json:"component_name"`
	Locale        string             `json:"locale"`
	Value         string             `json:"value"`
	Status        string             `json:"status"`
	Version       int64              `json:"version"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
	ChangedBy     pgtype.Int8        `json:"changed_by"`
	ChangedByName string             `json:"changed_by_name"`
}

func (q *Queries) ProjectHistory(ctx context.Context, projectID int64) ([]ProjectHistoryRow, error) {
	rows, err := q.db.Query(ctx, projectHistory, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectHistoryRow{}
	for rows.Next() {
		var i ProjectHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Key,
			&i.ComponentID,
			&i.ComponentName,
			&i.Locale,
			&i.Value,
			&i.Status,
			&i.Version,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectLocales = `-- name: ProjectLocales :many
SELECT pl.locale AS code, l.name FROM project_locales pl JOIN locales l ON l.code=pl.locale WHERE pl.project_id=$1 ORDER BY pl.locale
`

type ProjectLocalesRow struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) ProjectLocales(ctx context.Context, projectID int64) ([]ProjectLocalesRow, error) {
	rows, err := q.db.Query(ctx, projectLocales, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectLocalesRow{}
	for rows.Next() {
		var i ProjectLocalesRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectStats = `-- name: ProjectStats :many
SELECT c.id AS component_id, pl.locale,
 count(u.id)::bigint AS total,
 count(t.unit_id) FILTER (WHERE t.status IN ('translated','reviewed'))::bigint AS translated,
 count(t.unit_id) FILTER (WHERE t.status = 'reviewed')::bigint AS reviewed,
 count(t.unit_id) FILTER (WHERE t.status = 'needs_review')::bigint AS needs_review
FROM components c JOIN project_locales pl ON pl.project_id=c.project_id
LEFT JOIN units u ON u.component_id=c.id
LEFT JOIN translations t ON t.unit_id=u.id AND t.locale=pl.locale
WHERE c.project_id=$1 GROUP BY c.id, pl.locale ORDER BY c.id, pl.locale
`

type ProjectStatsRow struct {
	ComponentID int64  `json:"component_id"`
	Locale      string `json:"locale"`
	Total       int64  `json:"total"`
	Translated  int64  `json:"translated"`
	Reviewed    int64  `json:"reviewed"`
	NeedsReview int64  `json:"needs_review"`
}

func (q *Queries) ProjectStats(ctx context.Context, projectID int64) ([]ProjectStatsRow, error) {
	rows, err := q.db.Query(ctx, projectStats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectStatsRow{}
	for rows.Next() {
		var i ProjectStatsRow
		if err := rows.Scan(
			&i.ComponentID,
			&i.Locale,
			&i.Total,
			&i.Translated,
			&i.Reviewed,
			&i.NeedsReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectLocale = `-- name: RemoveProjectLocale :exec
DELETE FROM project_locales WHERE project_id=$1 AND locale=$2
`

type RemoveProjectLocaleParams struct {
	ProjectID int64  `json:"project_id"`
	Locale    string `json:"locale"`
}

func (q *Queries) RemoveProjectLocale(ctx context.Context, arg RemoveProjectLocaleParams) error {
	_, err := q.db.Exec(ctx, removeProjectLocale, arg.ProjectID, arg.Locale)
	return err
}

const renameProject = `-- name: RenameProject :one
UPDATE projects SET name=$2 WHERE id=$1 RETURNING id, slug, name, source_locale, created_at
`

type RenameProjectParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) RenameProject(ctx context.Context, arg RenameProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, renameProject, arg.ID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.SourceLocale,
		&i.CreatedAt,
	)
	return i, err
}

const repositoriesByURL = `-- name: RepositoriesByURL :many
SELECT id, project_id, name, url, branch, created_at FROM repositories WHERE url=$1 ORDER BY id
`

func (q *Queries) RepositoriesByURL(ctx context.Context, url string) ([]Repository, error) {
	rows, err := q.db.Query(ctx, repositoriesByURL, url)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Url,
			&i.Branch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repositoryComponents = `-- name: RepositoryComponents :many
SELECT id, project_id, slug, name, format, file_pattern, repository_id FROM components WHERE repository_id=$1 ORDER BY id
`

func (q *Queries) RepositoryComponents(ctx context.Context, repositoryID pgtype.Int8) ([]Component, error) {
	rows, err := q.db.Query(ctx, repositoryComponents, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.Format,
			&i.FilePattern,
			&i.RepositoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryDelivery = `-- name: RetryDelivery :execrows
UPDATE webhook_deliveries SET status='pending',error='' WHERE delivery_id=$1 AND status='failed'
`

func (q *Queries) RetryDelivery(ctx context.Context, deliveryID string) (int64, error) {
	result, err := q.db.Exec(ctx, retryDelivery, deliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveDocument = `-- name: SaveDocument :exec
INSERT INTO documents (component_id,locale,content) VALUES ($1,$2,$3) ON CONFLICT (component_id,locale) DO UPDATE SET content=excluded.content
`

type SaveDocumentParams struct {
	ComponentID int64  `json:"component_id"`
	Locale      string `json:"locale"`
	Content     []byte `json:"content"`
}

func (q *Queries) SaveDocument(ctx context.Context, arg SaveDocumentParams) error {
	_, err := q.db.Exec(ctx, saveDocument, arg.ComponentID, arg.Locale, arg.Content)
	return err
}

const saveGlossaryTerm = `-- name: SaveGlossaryTerm :one
INSERT INTO glossary_terms (project_id,locale,term,translation,note,updated_by) VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (project_id,locale,lower(term)) DO UPDATE SET term=excluded.term,translation=excluded.translation,note=excluded.note,updated_by=excluded.updated_by,updated_at=now() RETURNING id, project_id, locale, term, translation, note, updated_by, updated_at
`

type SaveGlossaryTermParams struct {
	ProjectID   int64       `json:"project_id"`
	Locale      string      `json:"locale"`
	Term        string      `json:"term"`
	Translation string      `json:"translation"`
	Note        string      `json:"note"`
	UpdatedBy   pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) SaveGlossaryTerm(ctx context.Context, arg SaveGlossaryTermParams) (GlossaryTerm, error) {
	row := q.db.QueryRow(ctx, saveGlossaryTerm,
		arg.ProjectID,
		arg.Locale,
		arg.Term,
		arg.Translation,
		arg.Note,
		arg.UpdatedBy,
	)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Locale,
		&i.Term,
		&i.Translation,
		&i.Note,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const saveLocale = `-- name: SaveLocale :one
INSERT INTO locales (code,name) VALUES ($1,$2) ON CONFLICT (code) DO UPDATE SET name=excluded.name RETURNING code, name
`

type SaveLocaleParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) SaveLocale(ctx context.Context, arg SaveLocaleParams) (Locale, error) {
	row := q.db.QueryRow(ctx, saveLocale, arg.Code, arg.Name)
	var i Locale
	err := row.Scan(&i.Code, &i.Name)
	return i, err
}

const saveMember = `-- name: SaveMember :exec
INSERT INTO memberships (project_id,user_id,role) VALUES ($1,$2,$3) ON CONFLICT (project_id,user_id) DO UPDATE SET role=excluded.role
`

type SaveMemberParams struct {
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
}

func (q *Queries) SaveMember(ctx context.Context, arg SaveMemberParams) error {
	_, err := q.db.Exec(ctx, saveMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const saveTranslation = `-- name: SaveTranslation :one
INSERT INTO translations (unit_id,locale,value,status,updated_by)
SELECT $1,$2,$3,$4,$5 WHERE $6::bigint=0
ON CONFLICT (unit_id,locale) DO NOTHING RETURNING unit_id, locale, value, status, version, updated_by, updated_at
`

type SaveTranslationParams struct {
	UnitID          int64       `json:"unit_id"`
	Locale          string      `json:"locale"`
	Value           string      `json:"value"`
	Status          string      `json:"status"`
	UpdatedBy       pgtype.Int8 `json:"updated_by"`
	ExpectedVersion int64       `json:"expected_version"`
}

func (q *Queries) SaveTranslation(ctx context.Context, arg SaveTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, saveTranslation,
		arg.UnitID,
		arg.Locale,
		arg.Value,
		arg.Status,
		arg.UpdatedBy,
		arg.ExpectedVersion,
	)
	var i Translation
	err := row.Scan(
		&i.UnitID,
		&i.Locale,
		&i.Value,
		&i.Status,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionUser = `-- name: SessionUser :one
SELECT u.id,u.email,u.name,u.admin FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at > now()
`

type SessionUserRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
	Admin bool   `json:"admin"`
}

func (q *Queries) SessionUser(ctx context.Context, tokenHash string) (SessionUserRow, error) {
	row := q.db.QueryRow(ctx, sessionUser, tokenHash)
	var i SessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Admin,
	)
	return i, err
}

const translationMemory = `-- name: TranslationMemory :many
SELECT DISTINCT ON (u.source, t.value) u.source, t.value, t.status, c.name AS component_name, p.name AS project_name,
 similarity(u.source, $1)::real AS score
FROM units u JOIN translations t ON t.unit_id=u.id AND t.locale=$2
JOIN components c ON c.id=u.component_id JOIN projects p ON p.id=c.project_id
WHERE u.id <> $3 AND t.value <> '' AND (u.source = $1 OR u.source % $1)
 AND ($4::boolean OR EXISTS (SELECT 1 FROM memberships m WHERE m.project_id=p.id AND m.user_id=$5))
ORDER BY u.source, t.value, t.status DESC LIMIT 50
`

type TranslationMemoryParams struct {
	Source  string `json:"source"`
	Locale  string `json:"locale"`
	UnitID  int64  `json:"unit_id"`
	IsAdmin bool   `json:"is_admin"`
	UserID  int64  `json:"user_id"`
}

type TranslationMemoryRow struct {
	Source        string  `json:"source"`
	Value         string  `json:"value"`
	Status        string  `json:"status"`
	ComponentName string  `json:"component_name"`
	ProjectName   string  `json:"project_name"`
	Score         float32 `json:"score"`
}

func (q *Queries) TranslationMemory(ctx context.Context, arg TranslationMemoryParams) ([]TranslationMemoryRow, error) {
	rows, err := q.db.Query(ctx, translationMemory,
		arg.Source,
		arg.Locale,
		arg.UnitID,
		arg.IsAdmin,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranslationMemoryRow{}
	for rows.Next() {
		var i TranslationMemoryRow
		if err := rows.Scan(
			&i.Source,
			&i.Value,
			&i.Status,
			&i.ComponentName,
			&i.ProjectName,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitHistory = `-- name: UnitHistory :many
SELECT h.id,h.value,h.status,h.version,h.changed_at,h.changed_by,coalesce(u.name,'')::text AS changed_by_name
FROM translation_history h LEFT JOIN users u ON u.id=h.changed_by
WHERE h.unit_id=$1 AND h.locale=$2 ORDER BY h.id DESC LIMIT 50
`

type UnitHistoryParams struct {
	UnitID int64  `json:"unit_id"`
	Locale string `json:"locale"`
}

type UnitHistoryRow struct {
	ID            int64              `json:"id"`
	Value         string             `json:"value"`
	Status        string             `json:"status"`
	Version       int64              `json:"version"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
	ChangedBy     pgtype.Int8        `json:"changed_by"`
	ChangedByName string             `json:"changed_by_name"`
}

func (q *Queries) UnitHistory(ctx context.Context, arg UnitHistoryParams) ([]UnitHistoryRow, error) {
	rows, err := q.db.Query(ctx, unitHistory, arg.UnitID, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitHistoryRow{}
	for rows.Next() {
		var i UnitHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Status,
			&i.Version,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components SET name=$2,repository_id=$3,file_pattern=$4 WHERE id=$1 RETURNING id, project_id, slug, name, format, file_pattern, repository_id
`

type UpdateComponentParams struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	RepositoryID pgtype.Int8 `json:"repository_id"`
	FilePattern  string      `json:"file_pattern"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.ID,
		arg.Name,
		arg.RepositoryID,
		arg.FilePattern,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.Format,
		&i.FilePattern,
		&i.RepositoryID,
	)
	return i, err
}

const updateTranslation = `-- name: UpdateTranslation :one
UPDATE translations SET value=$1,status=$2,version=version+1,updated_by=$3,updated_at=now()
WHERE unit_id=$4 AND locale=$5 AND version=$6 RETURNING unit_id, locale, value, status, version, updated_by, updated_at
`

type UpdateTranslationParams struct {
	Value           string      `json:"value"`
	Status          string      `json:"status"`
	UpdatedBy       pgtype.Int8 `json:"updated_by"`
	UnitID          int64       `json:"unit_id"`
	Locale          string      `json:"locale"`
	ExpectedVersion int64       `json:"expected_version"`
}

func (q *Queries) UpdateTranslation(ctx context.Context, arg UpdateTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, updateTranslation,
		arg.Value,
		arg.Status,
		arg.UpdatedBy,
		arg.UnitID,
		arg.Locale,
		arg.ExpectedVersion,
	)
	var i Translation
	err := row.Scan(
		&i.UnitID,
		&i.Locale,
		&i.Value,
		&i.Status,
		&i.Version,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUnit = `-- name: UpsertUnit :one
INSERT INTO units (component_id,key,source) VALUES ($1,$2,$3) ON CONFLICT (component_id,key) DO UPDATE SET source=excluded.source RETURNING id, component_id, key, source
`

type UpsertUnitParams struct {
	ComponentID int64  `json:"component_id"`
	Key         string `json:"key"`
	Source      string `json:"source"`
}

func (q *Queries) UpsertUnit(ctx context.Context, arg UpsertUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, upsertUnit, arg.ComponentID, arg.Key, arg.Source)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.ComponentID,
		&i.Key,
		&i.Source,
	)
	return i, err
}
