// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Component struct {
	ID           int64       `json:"id"`
	ProjectID    int64       `json:"project_id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	Format       string      `json:"format"`
	FilePattern  string      `json:"file_pattern"`
	RepositoryID pgtype.Int8 `json:"repository_id"`
}

type Document struct {
	ComponentID int64  `json:"component_id"`
	Locale      string `json:"locale"`
	Content     []byte `json:"content"`
}

type GlossaryTerm struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	Locale      string             `json:"locale"`
	Term        string             `json:"term"`
	Translation string             `json:"translation"`
	Note        string             `json:"note"`
	UpdatedBy   pgtype.Int8        `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ImportIssue struct {
	ComponentID int64              `json:"component_id"`
	Locale      string             `json:"locale"`
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	SeenAt      pgtype.Timestamptz `json:"seen_at"`
}

type Locale struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Membership struct {
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
}

type Project struct {
	ID           int64              `json:"id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	SourceLocale string             `json:"source_locale"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ProjectLocale struct {
	ProjectID int64  `json:"project_id"`
	Locale    string `json:"locale"`
}

type Repository struct {
	ID        int64              `json:"id"`
	ProjectID int64              `json:"project_id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Branch    string             `json:"branch"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Translation struct {
	UnitID    int64              `json:"unit_id"`
	Locale    string             `json:"locale"`
	Value     string             `json:"value"`
	Status    string             `json:"status"`
	Version   int64              `json:"version"`
	UpdatedBy pgtype.Int8        `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TranslationHistory struct {
	ID        int64              `json:"id"`
	UnitID    int64              `json:"unit_id"`
	Locale    string             `json:"locale"`
	Value     string             `json:"value"`
	Status    string             `json:"status"`
	Version   int64              `json:"version"`
	ChangedBy pgtype.Int8        `json:"changed_by"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}

type Unit struct {
	ID          int64  `json:"id"`
	ComponentID int64  `json:"component_id"`
	Key         string `json:"key"`
	Source      string `json:"source"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Admin        bool               `json:"admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	DeliveryID    string             `json:"delivery_id"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	RepositoryUrl string             `json:"repository_url"`
	Ref           string             `json:"ref"`
	Status        string             `json:"status"`
	Error         string             `json:"error"`
}
